root: docs

​structure:  
    readme: example.md
    summary: SUMMARY.md​
    
redirects:  
    help: ./support.md
    coc: ./code-of-conduct.md
    javadoc: https://dev.leakyabstractions.com/result/javadoc/
