root: docs

​structure:  
  readme: docs/example.md
  summary: SUMMARY.md​
    
redirects:  
  help: ./support.md
  coc: ./code_of_conduct.md
  javadoc: https://dev.leakyabstractions.com/result/javadoc/
