
# Publish a Snapshot Release
name: Snapshot

on:
  push:
    branches:
    - 'main'

jobs:
  build:

    name: Publish snapshot
    runs-on: ubuntu-latest

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v4

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 21

    # ================================
    # GET CURRENT VERSION
    # ================================
    - name: Get current version
      id: properties
      run: echo "version=`./gradlew -q printProperty -Pkey=version`" >> $GITHUB_OUTPUT

    # ================================
    # PUBLISH
    # ================================
    - name: Publish snapshot
      if: endsWith(steps.properties.outputs.version, '-SNAPSHOT')
      env:
        ORG_GRADLE_PROJECT_githubUsername: ${{ secrets.PUBLISH_USERNAME }}
        ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.PUBLISH_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: publish -Psnapshot --info --scan
